# TASK #1: DEFINE SINGLE AND MULTI-DIMENSIONAL  NUMPY ARRAYS

In [48]:
# NumPy is a Linear Algebra Library used for multidimensional arrays
# NumPy brings the best of two worlds: (1) C/Fortran computational efficiency, (2) Python language easy syntax 

# Let's define a one-dimensional array 
import numpy as np
np.array([50,60,80,100,200,300,500,600])


array([ 50,  60,  80, 100, 200, 300, 500, 600])

In [5]:
# Let's create a numpy array from the list "my_list"
my_list=np.array([50,60,80,100,200,300,500,600])
print(my_list)


[ 50  60  80 100 200 300 500 600]


In [8]:
x2=input("Enter the Number")
x2=int(x2)
y2=np.random.randint(0,x2,10)
y2

Enter the Number2


array([1, 0, 0, 1, 1, 0, 0, 0, 1, 0])

In [9]:
# Multi-dimensional (Matrix definition) 
my_list1=np.array([[2,5,8],[7,3,6]])
print(my_list1)


[[2 5 8]
 [7 3 6]]


MINI CHALLENGE #1: 
- Write a code that creates the following 2x4 numpy array

```
[[3 7 9 3] 
[4 3 2 2]]
```

In [10]:
my_list2=np.array([[3,7,9,3],[4,3,2,2]])
print(my_list2)

[[3 7 9 3]
 [4 3 2 2]]


# TASK #2: LEVERAGE NUMPY BUILT-IN METHODS AND FUNCTIONS 

In [11]:
# "rand()" uniform distribution between 0 and 1
random=np.random.rand(20)
print(random)

[0.89148184 0.49982414 0.609422   0.46023119 0.85940706 0.53558886
 0.44567297 0.32756383 0.43201893 0.2968613  0.56896765 0.90672361
 0.26513636 0.33333988 0.6360807  0.31498914 0.34175252 0.03214625
 0.20198104 0.43384683]


In [12]:
# you can create a matrix of random number as well
np.random.rand(3,3)

array([[0.30759928, 0.13302406, 0.85630166],
       [0.55561383, 0.87462715, 0.16683563],
       [0.40088216, 0.33989574, 0.3121817 ]])

In [13]:
# "randint" is used to generate random integers between upper and lower bounds
x=np.random.randint(1,100)
x

35

In [14]:
# "randint" can be used to generate a certain number of random itegers as follows
np.random.randint(1,100,15)

array([15, 91, 20, 99, 86, 69, 89, 73, 27, 51, 68,  7, 55, 66, 35])

In [15]:
# np.arange creates an evenly spaced values within a given interval
np.arange(1,50)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34,
       35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49])

In [16]:
# create a diagonal of ones and zeros everywhere else
np.diag([1,1,1,1,1,1,1])


array([[1, 0, 0, 0, 0, 0, 0],
       [0, 1, 0, 0, 0, 0, 0],
       [0, 0, 1, 0, 0, 0, 0],
       [0, 0, 0, 1, 0, 0, 0],
       [0, 0, 0, 0, 1, 0, 0],
       [0, 0, 0, 0, 0, 1, 0],
       [0, 0, 0, 0, 0, 0, 1]])

In [17]:
# Matrix of ones
one=np.ones((7,7))
print(one)

[[1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1.]]


In [18]:
# Array of zeros
zero=np.zeros((1,7))
print(zero)


[[0. 0. 0. 0. 0. 0. 0.]]


MINI CHALLENGE #2:
- Write a code that takes in a positive integer "x" from the user and creates a 1x10 array with random numbers ranging from 0 to "x"
x=input("Enter a value: ")

x2=input("Enter the Number")
x2=int(x2)
y2=np.random.randint(0,x2,10)
y2

In [19]:
x2=input("Enter the Number")
x2=int(x2)
y2=np.random.randint(0,x2,10)
y2

Enter the Number3


array([2, 2, 1, 0, 2, 1, 1, 0, 0, 1])

# TASK #3: PERFORM MATHEMATICAL OPERATIONS IN NUMPY

In [34]:
# np.arange() returns an evenly spaced values within a given interval
np.arange(1,10)


array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [35]:
np.arange(1,10,1)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [49]:
# Add 2 numpy arrays together
arr1=np.array([2,4,8,10,12])
arr2=np.array([10,12,14,16,18])
arr3=arr1+arr2
arr3


array([12, 16, 22, 26, 30])

array([ 1,  4,  9, 16, 25, 36, 49, 64, 81], dtype=int32)

array([1., 2., 3., 4., 5., 6., 7., 8., 9.])

array([2.71828183e+00, 7.38905610e+00, 2.00855369e+01, 5.45981500e+01,
       1.48413159e+02, 4.03428793e+02, 1.09663316e+03, 2.98095799e+03,
       8.10308393e+03])

MINI CHALLENGE #3:
- Given the X and Y values below, obtain the distance between them

```
X = [5, 7, 20]
Y = [9, 15, 4]
```

In [25]:
x4=np.array([5,7,20])
y4=np.array([9,15,4])
distance = np.linalg.norm(x4 - y4)
print(distance)

18.33030277982336


# TASK #4: PERFORM ARRAYS SLICING AND INDEXING 

In [4]:
x6=np.array([3,5,6,2,8,10,20,30,50])
x6

array([ 3,  5,  6,  2,  8, 10, 20, 30, 50])

In [5]:
# Access specific index from the numpy array
x6[0]

3

In [8]:
# Starting from the first index 0 up until and NOT including the last element
x6[0:3]

array([3, 5, 6])

In [15]:
# Broadcasting, altering several values in a numpy array at once
x6[0:4]=7
x6

array([ 7,  7,  7,  7,  8, 10, 20, 30, 50])

In [12]:
# Let's define a two dimensional numpy array
x7=np.array([[6,9,7,1],[6,5,5,5], [6,9,1,8],[8,9,3,1]])
x7

array([[6, 9, 7, 1],
       [6, 5, 5, 5],
       [6, 9, 1, 8],
       [8, 9, 3, 1]])

In [13]:
# Get a row from a mtrix
x7[0,0:4]

array([6, 9, 7, 1])

In [14]:
# Get one element
x7[0,2]

7

MINI CHALLENGE #4:
- In the following matrix, replace the last row with 0

```
X = [2 30 20 -2 -4]
    [3 4  40 -3 -2]
    [-3 4 -6 90 10]
    [25 45 34 22 12]
    [13 24 22 32 37]
```



In [19]:
x10=np.random.randint(1,30,(5,5))
x10[4,0:5]=0
print(x10)

[[17  6 14 23 11]
 [16  8 23  8 29]
 [ 8  4  5  8  2]
 [27  7  5  1 27]
 [ 0  0  0  0  0]]


# TASK #5: PERFORM ELEMENTS SELECTION (CONDITIONAL)

In [20]:
x11=np.random.randint(1,50,(5,5))
x11

array([[34,  9, 46, 33,  1],
       [33, 30, 30, 31, 43],
       [ 7, 19, 42,  7, 28],
       [43, 27, 18, 34, 33],
       [46,  9, 11, 39, 48]])

In [34]:
x11=x11[x11<40]
x11

array([ 9, 33,  1, 33, 31,  7, 19,  7, 27, 33,  9, 11, 39])

In [33]:
# Obtain odd elements only
x11=x11[x11%2 !=0]
x11

array([ 9, 33,  1, 33, 31, 43,  7, 19,  7, 43, 27, 33,  9, 11, 39])

MINI CHALLENGE #5:
- In the following matrix, replace negative elements by 0 and replace odd elements with -2


```
X = [2 30 20 -2 -4]
    [3 4  40 -3 -2]
    [-3 4 -6 90 10]
    [25 45 34 22 12]
    [13 24 22 32 37]
```


In [32]:
x5=np.array([[2,30,20,-2,-4],[3,4,40,-3,-2],[-3,4,-6,90,10],[25,45,34,22,12],[13,24,22,32,37]])
x5[x5<1]=0
x5[x5 % 2 != 0] = -2
print(x5)

[[ 2 30 20  0  0]
 [-2  4 40  0  0]
 [ 0  4  0 90 10]
 [-2 -2 34 22 12]
 [-2 24 22 32 -2]]


# TASK #6: UNDERSTAND PANDAS FUNDAMENTALS

In [ ]:
# Pandas is a data manipulation and analysis tool that is built on Numpy.
# Pandas uses a data structure known as DataFrame (think of it as Microsoft excel in Python). 
# DataFrames empower programmers to store and manipulate data in a tabular fashion (rows and columns).
# Series Vs. DataFrame? Series is considered a single column of a DataFrame.

In [2]:
import pandas as pd

In [3]:
# Let's define a two-dimensional Pandas DataFrame
# Note that you can create a pandas dataframe from a python dictionary
x12=pd.DataFrame({"Bank client ID":[111,222,333,444],
                  "Bank Client Name":['channel','sam','fridge','ram'],
                  "Net worth [$]":[22,333,444,222],
                  "Years with bank":[2,2,2,2]
                 })
print(x12)

   Bank client ID Bank Client Name  Net worth [$]  Years with bank
0             111          channel             22                2
1             222              sam            333                2
2             333           fridge            444                2
3             444              ram            222                2


In [4]:
# Let's obtain the data type 
x12.dtypes

Bank client ID       int64
Bank Client Name    object
Net worth [$]        int64
Years with bank      int64
dtype: object

In [5]:
# you can only view the first couple of rows using .head()
x12.head(2)

,Bank client ID,Bank Client Name,Net worth [$],Years with bank
0,111,channel,22,2
1,222,sam,333,2


In [6]:
# you can only view the last couple of rows using .tail()
x12.tail(1)

,Bank client ID,Bank Client Name,Net worth [$],Years with bank
3,444,ram,222,2


MINI CHALLENGE #6:
- A porfolio contains a collection of securities such as stocks, bonds and ETFs. Define a dataframe named 'portfolio_df' that holds 3 different stock ticker symbols, number of shares, and price per share (feel free to choose any stocks)
- Calculate the total value of the porfolio including all stocks

In [7]:
portfolio_df = pd.DataFrame({
    'Ticker': ['AAPL', 'MSFT', 'TSLA'],
    'Shares': [10, 5, 8],
    'Price_per_Share': [190.50, 425.75, 250.30]
})
portfolio_df['Total_Value'] = portfolio_df['Shares'] * portfolio_df['Price_per_Share']
totalvalueoftheporfolio=portfolio_df['Total_Value'].sum()
print(f"The Total Value of the Portfolio : {totalvalueoftheporfolio}.")

The Total Value of the Portfolio : 6036.15.


# TASK #7: PANDAS WITH CSV AND HTML DATA

In [8]:
# Pandas is used to read a csv file and store data in a DataFrame


In [41]:
! pip install lxml


[notice] A new release of pip is available: 24.0 -> 26.1.2
[notice] To update, run: pip install --upgrade pip


In [43]:
# Read tabular data using read_html
!python -m pip install --upgrade pip

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.8/1.8 MB 70.7 MB/s eta 0:00:00
  Attempting uninstall: pip
    Found existing installation: pip 24.0
    Uninstalling pip-24.0:
      Successfully uninstalled pip-24.0


MINI CHALLENGE #7:
- Write a code that uses Pandas to read tabular US retirement data
- You can use data from here: https://www.ssa.gov/oact/progdata/nra.html 

In [46]:
import requests
url = "https://www.ssa.gov/oact/progdata/nra.html"
headers = {
    "User-Agent": "Mozilla/5.0"
}
response = requests.get(url, headers=headers)

print(response.status_code)   # Should ideally be 200

tables = pd.read_html(response.text)

403


ValueError: No tables found

# TASK #8: PANDAS OPERATIONS

In [26]:
# Let's define a dataframe as follows:
# Let's define a dataframe as follows:
bank_client_df = pd.DataFrame({'Bank client ID':[111, 222, 333, 444], 
                               'Bank Client Name':['Chanel', 'Steve', 'Mitch', 'Ryan'], 
                               'Net worth [$]':[3500, 29000, 10000, 2000], 
                               'Years with bank':[3, 4, 9, 5]})
bank_client_df

,Bank client ID,Bank Client Name,Net worth [$],Years with bank
0,111,Chanel,3500,3
1,222,Steve,29000,4
2,333,Mitch,10000,9
3,444,Ryan,2000,5


In [27]:
# Pick certain rows that satisfy a certain criteria 
bank_client_df

,Bank client ID,Bank Client Name,Net worth [$],Years with bank
0,111,Chanel,3500,3
1,222,Steve,29000,4
2,333,Mitch,10000,9
3,444,Ryan,2000,5


In [31]:
# Delete a column from a DataFrame
bank_client_df

,Bank client ID,Bank Client Name,Net worth [$]
0,111,Chanel,3500
1,222,Steve,29000
2,333,Mitch,10000
3,444,Ryan,2000


MINI CHALLENGE #8:
- Using "bank_client_df" DataFrame, leverage pandas operations to only select high networth individuals with minimum $5000 
- What is the combined networth for all customers with 5000+ networth?

In [39]:
sum=0
high_income_clients=bank_client_df[bank_client_df['Net worth [$]']>=5000]
high_income_clients['Net worth [$]'].sum()


39000

# TASK #9: PANDAS WITH FUNCTIONS

In [4]:
# Let's define a dataframe as follows:
bank_client_df = pd.DataFrame({'Bank client ID':[111, 222, 333, 444], 
                               'Bank Client Name':['Chanel', 'Steve', 'Mitch', 'Ryan'], 
                               'Net worth [$]':[3500, 29000, 10000, 2000], 
                               'Years with bank':[3, 4, 9, 5]})
bank_client_df

,Bank client ID,Bank Client Name,Net worth [$],Years with bank
0,111,Chanel,3500,3
1,222,Steve,29000,4
2,333,Mitch,10000,9
3,444,Ryan,2000,5


In [18]:
def increase(balance):
    return balance *1.2

In [19]:
# You can apply a function to the DataFrame 
bank_client_df['Net worth [$]'].apply(increase)

0     4200.0
1    34800.0
3     2400.0
2    12000.0
Name: Net worth [$], dtype: float64

In [25]:
bank_client_df['Bank Client Name'].apply(len)

0    6
1    5
3    4
2    5
Name: Bank Client Name, dtype: int64

MINI CHALLENGE #9:
- Define a function that triples the stock prices and adds $200
- Apply the function to the DataFrame
- Calculate the updated total networth of all clients combined

In [24]:
def increase1(balance):
    return balance*3+200
bank_client_df['Net worth [$]'].apply(increase1)

0    10700
1    87200
3     6200
2    30200
Name: Net worth [$], dtype: int64

# TASK #10: PERFORM SORTING AND ORDERING IN PANDAS

In [15]:

bank_client_df = pd.DataFrame({'Bank client ID':[111, 222, 333, 444], 
                               'Bank Client Name':['Chanel', 'Steve', 'Mitch', 'Ryan'], 
                               'Net worth [$]':[3500, 29000, 10000, 2000], 
                               'Years with bank':[3, 4, 9, 5]})
bank_client_df

,Bank client ID,Bank Client Name,Net worth [$],Years with bank
0,111,Chanel,3500,3
1,222,Steve,29000,4
2,333,Mitch,10000,9
3,444,Ryan,2000,5


In [16]:
# You can sort the values in the dataframe according to number of years with bank
bank_client_df.sort_values(by="Years with bank",inplace=True)

In [17]:
# Note that nothing changed in memory! you have to make sure that inplace is set to True
bank_client_df

,Bank client ID,Bank Client Name,Net worth [$],Years with bank
0,111,Chanel,3500,3
1,222,Steve,29000,4
3,444,Ryan,2000,5
2,333,Mitch,10000,9


In [83]:
# Set inplace = True to ensure that change has taken place in memory 


In [84]:
# Note that now the change (ordering) took place 


,Bank client ID,Bank Client Name,Net worth [$],Years with bank
0,111,Chanel,3500,3
1,222,Steve,29000,4
3,444,Ryan,2000,5
2,333,Mitch,10000,9


# TASK #11: PERFORM CONCATENATING AND MERGING WITH PANDAS

In [90]:
# Check this out: https://pandas.pydata.org/pandas-docs/stable/user_guide/merging.html

In [59]:
df1=pd.DataFrame({
    'A':['A0','A1','A2','A3'],
    'B':['B0','B1','B2','B3'],
    'C':['C0','C1','C2','C3'],
    'D':['D0','D1','D2','D3']
})
df1

,A,B,C,D
0,A0,B0,C0,D0
1,A1,B1,C1,D1
2,A2,B2,C2,D2
3,A3,B3,C3,D3


,A,B,C,D
0,A0,B0,C0,D0
1,A1,B1,C1,D1
2,A2,B2,C2,D2
3,A3,B3,C3,D3


In [62]:
df2 = pd.DataFrame({
    'A': ['A4', 'A5', 'A6', 'A7'],
    'B': ['B4', 'B5', 'B6', 'B7'],
    'C': ['C4', 'C5', 'C6', 'C7'],
    'D': ['D4', 'D5', 'D6', 'D7']
})
df2

,A,B,C,D
0,A4,B4,C4,D4
1,A5,B5,C5,D5
2,A6,B6,C6,D6
3,A7,B7,C7,D7


,A,B,C,D
4,A4,B4,C4,D4
5,A5,B5,C5,D5
6,A6,B6,C6,D6
7,A7,B7,C7,D7


In [64]:
df3 = pd.DataFrame({
    'A': ['A8', 'A9', 'A10', 'A11'],
    'B': ['B8', 'B9', 'B10', 'B11'],
    'C': ['C8', 'C9', 'C10', 'C11'],
    'D': ['D8', 'D9', 'D10', 'D11']
})
df3

,A,B,C,D
0,A8,B8,C8,D8
1,A9,B9,C9,D9
2,A10,B10,C10,D10
3,A11,B11,C11,D11


In [66]:
dataframe=[df1,df2,df3]
pd.concat(dataframe)

,A,B,C,D
0,A0,B0,C0,D0
1,A1,B1,C1,D1
2,A2,B2,C2,D2
3,A3,B3,C3,D3
0,A4,B4,C4,D4
1,A5,B5,C5,D5
2,A6,B6,C6,D6
3,A7,B7,C7,D7
0,A8,B8,C8,D8
1,A9,B9,C9,D9


# TASK #12: PROJECT AND CONCLUDING REMARKS

- Define a dataframe named 'Bank_df_1' that contains the first and last names for 5 bank clients with IDs = 1, 2, 3, 4, 5 
- Assume that the bank got 5 new clients, define another dataframe named 'Bank_df_2' that contains a new clients with IDs = 6, 7, 8, 9, 10
- Let's assume we obtained additional information (Annual Salary) about all our bank customers (10 customers) 
- Concatenate both 'bank_df_1' and 'bank_df_2' dataframes
- Merge client names and their newly added salary information using the 'Bank Client ID'
- Let's assume that you became a new client to the bank
- Define a new DataFrame that contains your information such as client ID (choose 11), first name, last name, and annual salary.
- Add this new dataframe to the original dataframe 'bank_df_all'.

In [82]:
import pandas as pd

Bank_df_1 = pd.DataFrame(
    {
        'First Name': ['John', 'Jane', 'Mike', 'Sarah', 'David'],
        'Last Name': ['Smith', 'Doe', 'Brown', 'Wilson', 'Lee'],
        'Bank Client ID':[1,2,3,4,5]
    }
)

Bank_df_2 = pd.DataFrame(
    {
        'First Name': ['Emily', 'Chris', 'Anna', 'James', 'Linda'],
        'Last Name': ['Taylor', 'White', 'Green', 'Hall', 'King'],
        'Bank Client ID':[6,7,8,9,10]
    }
)
Annualsalary=pd.DataFrame({
    'Bank Client ID':[1,2,3,4,5,6,7,8,9,10],
    'Annual Salary':[1,2,3,4,5,6,7,8,9,10]
})
myinfo=pd.DataFrame({
    'First Name':['Awais'],
    'Last Name':['Imran'],
    'Bank Client ID':[11],
    'Annual Salary':[12000]
})
myinfo
data=[Bank_df_1,Bank_df_2]
data1=pd.concat(data)
data=pd.merge(data1, Annualsalary, on='Bank Client ID')
data
data2=[data,myinfo]
pd.concat(data2)

,First Name,Last Name,Bank Client ID,Annual Salary
0,John,Smith,1,1
1,Jane,Doe,2,2
2,Mike,Brown,3,3
3,Sarah,Wilson,4,4
4,David,Lee,5,5
5,Emily,Taylor,6,6
6,Chris,White,7,7
7,Anna,Green,8,8
8,James,Hall,9,9
9,Linda,King,10,10


# EXCELLENT JOB!

# MINI CHALLENGES SOLUTIONS

MINI CHALLENGE #1 SOLUTION: 
- Write a code that creates the following 2x4 numpy array

```
[[3 7 9 3] 
[4 3 2 2]]
```

In [5]:
x = np.array([[[3, 7, 9, 3] , [4, 3, 2, 2]]])
x

array([[[3, 7, 9, 3],
        [4, 3, 2, 2]]])

MINI CHALLENGE #2 SOLUTION:
- Write a code that takes in a positive integer "x" from the user and creates a 1x10 array with random numbers ranging from 0 to "x"

In [15]:
x = int(input("Please enter a positive integer value: "))
x = np.random.randint(1, x, 10)
x

Please enter a positive integer value: 7


array([6, 5, 3, 5, 4, 2, 3, 3, 2, 1])

MINI CHALLENGE #3 SOLUTION:
- Given the X and Y values below, obtain the distance between them


```
X = [5, 7, 20]
Y = [9, 15, 4]
```




In [22]:
X = np.array([5, 7, 20])
Y = np.array([9, 15, 4])
Z = np.sqrt(X**2 + Y**2)
Z

array([10.29563014, 16.55294536, 20.39607805])

MINI CHALLENGE #4 SOLUTION:
- In the following matrix, replace the last row with 0

```
X = [2 30 20 -2 -4]
    [3 4  40 -3 -2]
    [-3 4 -6 90 10]
    [25 45 34 22 12]
    [13 24 22 32 37]
```




In [33]:
X = np.array([[2, 30, 20, -2, -4],
    [3, 4,  40, -3, -2],
    [-3, 4, -6, 90, 10],
    [25, 45, 34, 22, 12],
    [13, 24, 22, 32, 37]])


In [34]:
X[4] = 0
X

array([[ 2, 30, 20, -2, -4],
       [ 3,  4, 40, -3, -2],
       [-3,  4, -6, 90, 10],
       [25, 45, 34, 22, 12],
       [ 0,  0,  0,  0,  0]])

MINI CHALLENGE #5 SOLUTION:
- In the following matrix, replace negative elements by 0 and replace odd elements with -2


```
X = [2 30 20 -2 -4]
    [3 4  40 -3 -2]
    [-3 4 -6 90 10]
    [25 45 34 22 12]
    [13 24 22 32 37]
```

In [41]:
X = np.array([[2, 30, 20, -2, -4],
    [3, 4,  40, -3, -2],
    [-3, 4, -6, 90, 10],
    [25, 45, 34, 22, 12],
    [13, 24, 22, 32, 37]])

X[X<0] = 0
X[X%2==1] = -2
X

array([[ 2, 30, 20,  0,  0],
       [-2,  4, 40,  0,  0],
       [ 0,  4,  0, 90, 10],
       [-2, -2, 34, 22, 12],
       [-2, 24, 22, 32, -2]])

MINI CHALLENGE #6 SOLUTION:
- A porfolio contains a collection of securities such as stocks, bonds and ETFs. Define a dataframe named 'portfolio_df' that holds 3 different stock ticker symbols, number of shares, and price per share (feel free to choose any stocks)
- Calculate the total value of the porfolio including all stocks

In [58]:
portfolio_df = pd.DataFrame({'stock ticker symbols':['AAPL', 'AMZN', 'T'],
                             'price per share [$]':[3500, 200, 40], 
                             'Number of stocks':[3, 4, 9]})
portfolio_df

,stock ticker symbols,price per share [$],Number of stocks
0,AAPL,3500,3
1,AMZN,200,4
2,T,40,9


In [59]:
stocks_dollar_value = portfolio_df['price per share [$]'] * portfolio_df['Number of stocks']
print(stocks_dollar_value)
print('Total portfolio value = {}'.format(stocks_dollar_value.sum()))

0    10500
1      800
2      360
dtype: int64
Total portfolio value = 11660


MINI CHALLENGE #7 SOLUTION:
- Write a code that uses Pandas to read tabular US retirement data
- You can use data from here: https://www.ssa.gov/oact/progdata/nra.html 

In [ ]:
# Read tabular data using read_html
retirement_age_df = pd.read_html('https://www.ssa.gov/oact/progdata/nra.html')
retirement_age_df

MINI CHALLENGE #8 SOLUTION:
- Using "bank_client_df" DataFrame, leverage pandas operations to only select high networth individuals with minimum $5000 
- What is the combined networth for all customers with 5000+ networth?

In [ ]:
df_high_networth = bank_client_df[ (bank_client_df['Net worth [$]'] >= 5000) ]
df_high_networth

In [ ]:
df_high_networth['Net worth [$]'].sum()

MINI CHALLENGE #9 SOLUTION:
- Define a function that triples the stock prices and adds $200
- Apply the function to the DataFrame
- Calculate the updated total networth of all clients combined

In [77]:
def networth_update(balance):
    return balance * 3 + 200 

In [78]:
# You can apply a function to the DataFrame 
results = bank_client_df['Net worth [$]'].apply(networth_update)
results

0    10700
1    87200
2    30200
3     6200
Name: Net worth [$], dtype: int64

In [79]:
results.sum()

134300

PROJECT SOLUTION:

In [ ]:
# Creating a dataframe from a dictionary
# Let's define a dataframe with a list of bank clients with IDs = 1, 2, 3, 4, 5 

raw_data = {'Bank Client ID': ['1', '2', '3', '4', '5'],
            'First Name': ['Nancy', 'Alex', 'Shep', 'Max', 'Allen'], 
            'Last Name': ['Rob', 'Ali', 'George', 'Mitch', 'Steve']}

Bank_df_1 = pd.DataFrame(raw_data, columns = ['Bank Client ID', 'First Name', 'Last Name'])
Bank_df_1


# Let's define another dataframe for a separate list of clients (IDs = 6, 7, 8, 9, 10)
raw_data = {
        'Bank Client ID': ['6', '7', '8', '9', '10'],
        'First Name': ['Bill', 'Dina', 'Sarah', 'Heather', 'Holly'], 
        'Last Name': ['Christian', 'Mo', 'Steve', 'Bob', 'Michelle']}
Bank_df_2 = pd.DataFrame(raw_data, columns = ['Bank Client ID', 'First Name', 'Last Name'])
Bank_df_2


# Let's assume we obtained additional information (Annual Salary) about our bank customers 
# Note that data obtained is for all clients with IDs 1 to 10 
raw_data = {
        'Bank Client ID': ['1', '2', '3', '4', '5', '6', '7', '8', '9', '10'],
        'Annual Salary [$/year]': [25000, 35000, 45000, 48000, 49000, 32000, 33000, 34000, 23000, 22000]}
bank_df_salary = pd.DataFrame(raw_data, columns = ['Bank Client ID','Annual Salary [$/year]'])
bank_df_salary


# Let's concatenate both dataframes #1 and #2
# Note that we now have client IDs from 1 to 10
bank_df_all = pd.concat([Bank_df_1, Bank_df_2])
bank_df_all


# Let's merge all data on 'Bank Client ID'
bank_df_all = pd.merge(bank_df_all, bank_df_salary, on = 'Bank Client ID')
bank_df_all


In [104]:
new_client = {
        'Bank Client ID': ['11'],
        'First Name': ['Ry'], 
        'Last Name': ['Aly'],
        'Annual Salary [$/year]' : [1000]}
new_client_df = pd.DataFrame(new_client, columns = ['Bank Client ID', 'First Name', 'Last Name', 'Annual Salary [$/year]'])
new_client_df

,Bank Client ID,First Name,Last Name,Annual Salary [$/year]
0,11,Ry,Aly,1000


In [105]:
new_df = pd.concat([bank_df_all, new_client_df], axis = 0)
new_df

,Bank Client ID,First Name,Last Name,Annual Salary [$/year]
0,1,Nancy,Rob,25000
1,2,Alex,Ali,35000
2,3,Shep,George,45000
3,4,Max,Mitch,48000
4,5,Allen,Steve,49000
5,6,Bill,Christian,32000
6,7,Dina,Mo,33000
7,8,Sarah,Steve,34000
8,9,Heather,Bob,23000
9,10,Holly,Michelle,22000
